Update README.md
7094f5e6-351c-11ee-be56-0242ac120002/Taskify pull request #3
Opened 2023-08-22 17:22 UTC by LionShareZoki

Create initial readme on how to start a project locally

2023-08-22 21:08 UTC, dariomrk requested changes
The `README.md` should contain these sections:
- Heading (title)
- Description (what is this all about)
- Getting started (dev environment setup instructions)
  The dev setup instructions should contain the minimal amount of information to set up the repository for local development.
  The setup instructions should be logically ordered. It is very helpful if terminal commands are clearly formatted like `so`.

2023-08-22 21:08 UTC, dariomrk commented on frontend/README.md
> +# Vite React TypeScript Starter
Could we change this to something like `# Taskify Frontend`?

2023-08-23 16:38 UTC, LionShareZoki commented on frontend/README.md
> +# Vite React TypeScript Starter
Yep

2023-08-23 16:54 UTC, LionShareZoki commented on frontend/README.md
> +   `npm run dev`
If `git clone` will be in the root repo I will assume to make instructions after the whole project is cloned.

2023-08-23 17:01 UTC, LionShareZoki commented
I have made a new commit. Can you see it now? Is it pushed correctly since I have committed it directly on GitHub?

2023-08-24 17:07 UTC, merged